services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      OLLAMA_KEEP_ALIVE: -1
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    networks:
      - app-network
      - backbone
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  web:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d/
    networks:
      - backbone
  app:
    build: ./backend
    context: ./backend
    restart: unless-stopped
    container_name: app
    hostname: app
    ports:
      - "8000:8000"
    networks:
      - backbone

networks:
  app-network:
  backbone:
    driver: bridge
