services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      OLLAMA_KEEP_ALIVE: -1
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - app-network
      - backbone
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  web:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d/
    networks:
      - backbone
    depends_on:
      app:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./nginx.conf.d/
          target: /etc/nginx/conf.d/

  redis:
    image: redis:latest
    container_name: llm_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/root/redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=0
    networks:
      - redis-network

  app:
    build: ./backend
    restart: unless-stopped
    container_name: app
    hostname: app
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=ollama:11434
      - OLLAMA_MODEL=llama3.1
    networks:
      - redis-network
      - backbone
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    develop:
      watch:
        - action: sync
          path: ./backend/src/app
          target: /app/src/app
          ignore:
            - __pycache__/
            - "*.pyc"
            - logs/
        - action: rebuild
          path: ./backend/pyproject.toml
        - action: sync+restart
          path: ./backend/src/app/data/config.py
          target: /app/src/app/data/config.py

volumes:
  redis_data:
  ollama:
    
networks:
  app-network:
  backbone:
    driver: bridge
  redis-network:
