services:
  pg:
    image: postgres
    container_name: ai_pg
    hostname: pg.dev
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: ai_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - db-network

volumes:
  pgdata:

networks:
  app-network:
  db-network:
