services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      OLLAMA_KEEP_ALIVE: -1
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    networks:
      - app-network

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

networks:
  app-network:
