FROM python:3.12-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists/*
    
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the project into the image
COPY pyproject.toml uv.lock README.md /app/

# Sync the project into a new environment, using the frozen lockfile
WORKDIR /app
ENV PYTHONPATH "/app/src"
RUN uv sync --frozen
ADD src /app/src
CMD uv run litestar --app app.main:app run --debug --reload --host "0.0.0.0"
