FROM node:20 AS build_stage
WORKDIR /app
COPY ./frontend .
RUN npm install
RUN npm run build


FROM nginx:alpine3.20
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build_stage /app/dist .
RUN chown -R nginx:nginx .
EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]

